### ISSUE TITLE
the ctx.clearRect method doesn't work

### ISSUE THREAD

**Issue by zakariamouhid** [davidenke/context-filter-polyfill#10]
### bug preview
the ctx.clearRect method doesn't clear
https://jsfiddle.net/zakariamouhid/4wpmb3ut/2/

### solution
should simply call the original clearRect
https://github.com/davidenke/context-filter-polyfill/blob/17e4a910f3c523ad3cd2a74fad3bdf2405f4231b/src/patches/method.patches.ts#L22-L25
should add clearRect
```javascript
 // do not apply on mirror 
 if (this.canvas.__skipFilterPatch || member === 'clearRect') { 
   return original.call(this, ...args); 
 } 
```

### solution preview
https://jsfiddle.net/zakariamouhid/4wpmb3ut/3/

**Comment by davidenke** [comment]
@zakariamouhid I know it's been a while, but would you mind to open a PR?
