### ISSUE TITLE
Correct way to polyfill?

### ISSUE THREAD

**Issue by kainsavage** [davidenke/context-filter-polyfill#12]
Howdy, I could not figure out the right way to use this polyfill in an npm project (simple `create-react-app` for example).

Eventually, I copied the contents `node_modules/context-filter-polyfill/dist/index.js` into a `<script>` tag in my head, and *this worked* but feels like the wrong way to do it.

What's the correct way?

**Comment by TheBlindHawk** [comment]
Hey just sharing my method:
```
npm i context-filter-polyfill
```
then add 
```
import 'context-filter-polyfill/dist/index.js';
```
in your js file (or use require instead of import)
I think these two steps would be a nice thing to add to the README file : )

**Comment by davidenke** [comment]
> I think these two steps would be a nice thing to add to the README file : )

@TheBlindHawk you're right, would you mind to contribute a pr?

**Comment by donni106** [comment]
> ```
> import 'context-filter-polyfill/dist/index.js';
> ```

this should be the same as `import 'context-filter-polyfill'`

**Comment by TheBlindHawk** [comment]
@davidenke 
Sorry for not replying, turns out I had notifications off on github and the email didn't reach me.
Thanks for the offer anyways! : )

**Comment by davidenke** [comment]
@TheBlindHawk me too, that's why it took years for me to notice :P

I already updated the readme.
