### ISSUE TITLE
the ctx.fillRect method doesn't work

### ISSUE THREAD

**Issue by gopisf4061** [davidenke/context-filter-polyfill#24]
1. While using fillRect() on drawing, it draws at width of 300, 150 instead of canvas's width and height

 

Code Changes:

 

Bug Line:
![image](https://user-images.githubusercontent.com/95226111/228443895-f4654d6f-6966-4832-8ba0-e3175fcdae08.png)

 

Fix Line:
![image](https://user-images.githubusercontent.com/95226111/228443998-944d1832-5bd4-4eaa-8980-81380e00ca71.png)

 

2. Stroke color and fill color of context changes while calling setTransform() method in polyfill

 

Code Changes:

 

Bug:
![image](https://user-images.githubusercontent.com/95226111/228444385-09c45e4f-c598-4065-9349-32c9a014b9da.png)

 

Fix:
![image](https://user-images.githubusercontent.com/95226111/228444420-0d5607fb-6c6b-4fbe-b437-3088f5ae6e39.png)

**Comment by gopisf4061** [comment]
can you please update on this

**Comment by davidenke** [comment]
Would you please retry with 0.3.14
