### ISSUE TITLE
Polyfill for the OffscreenCanvasRenderingContext2D.filter

### ISSUE THREAD

**Issue by bekatan** [davidenke/context-filter-polyfill#32]
I am using an offscreencanvas with a webworker in my drawing application and offscreenContext.filter = blur()  is one of the effects.  Any plans to support this?

**Comment by davidenke** [comment]
Could you provide some reproduction please? Like a stackblitz or smth. else?

**Comment by bekatan** [comment]
Yes, the native OffscreenCanvas here 
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
The corresponding OffscreenCanvasRenderingContext2d supports most of the CanvasRenderingContext2d features including the context.filter
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D
Would be great to have a polyfill for it

**Comment by davidenke** [comment]
@bekatan shipped with 0.3.17. Honestly, I haven't tried from a worker yet, but everything works in for the [synchronous example](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas#synchronous_display_of_frames_produced_by_an_offscreencanvas).
