### ISSUE TITLE
shadowContext canvas is using the default canvas size of 300x150

### ISSUE THREAD

**Issue by zakariamouhid** [davidenke/context-filter-polyfill#9]
### bug preview
https://jsfiddle.net/zakariamouhid/4wpmb3ut/

### solution
set the shadowContext canvas size
```javascript
shadowContext.canvas.width = context.canvas.width;
shadowContext.canvas.height = context.canvas.height;
```
https://github.com/davidenke/context-filter-polyfill/blob/17e4a910f3c523ad3cd2a74fad3bdf2405f4231b/src/filters/drop-shadow.filter.ts#L6

### solution preview
https://jsfiddle.net/zakariamouhid/4wpmb3ut/1/

**Comment by davidenke** [comment]
@zakariamouhid I know it's been a while, but would you mind to open a PR?
